name: "Liferay Cloud Upgrade"
description: "Create a new branch and pull request if if a new versions for Liferay Cloud Docker images are available"
author: "lgdd"

branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  workspace-directory:
    description: >
      Path to your Liferay Cloud workspace if different from root directory.
      It will be use in this actions steps for the 'working-directory' directive.
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - uses: actions/setup-go@v4
      with:
        go-version: ">=1.20.0"
    - shell: bash
      env:
        UPGRADE_BRANCH_NAME: "upgrade-liferay-cloud-images"
      run: |
        NO_UPGRADE_BRANCH=$(git ls-remote -q | grep -q '${{ env.UPGRADE_BRANCH_NAME }}' && echo false || echo true)
        echo "NO_UPGRADE_BRANCH=$NO_UPGRADE_BRANCH" >> $GITHUB_ENV
    - run: go run main.go
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        WORKSPACE_DIRECTORY: ${{ inputs.workspace-directory }}
